CREATE TABLE user (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(32) UNIQUE NOT NULL,
	email VARCHAR(128) UNIQUE NOT NULL,
	password varchar(32) NOT NULL,
	access INT(1)
);

CREATE TABLE movie (
	id INT UNIQUE NOT NULL PRIMARY KEY,
	title VARCHAR(128) NOT NULL,
	rating VARCHAR(8) NOT NULL,
	year INT NOT NULL,
	runtime VARCHAR(32) NOT NULL,
	language VARCHAR(64),
	poster VARCHAR(128),
	genre VARCHAR(64) NOT NULL,
	description VARCHAR(191) NOT NULL
);
	
CREATE TABLE user_movie (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	movie_id INT NOT NULL
);

